"use client";


import { useCallback, useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import styles from "../../dashboard.module.css";
import { supabase } from "@/lib/supabase";
import { useLanguage } from "@/lib/i18n";

function getErrorMessage(detail, fallback) {
  if (Array.isArray(detail)) return detail[0]?.msg || fallback;
  if (typeof detail === "string") return detail;
  return fallback;
}

async function getAccessToken() {
  const { data } = await supabase.auth.getSession();
  return data.session?.access_token || null;
}

function escapeHtml(value) {
  return String(value ?? "")
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

function formatPdfValue(value, fallback = "-") {
  if (value === null || value === undefined || value === "") return fallback;
  return escapeHtml(value);
}

function getPlanTitle(plan, aiPlan) {
  return plan.title || aiPlan?.title || "Untitled Plan";
}

function getPdfFileName(title) {
  const safeTitle = title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 60);

  return `${safeTitle || "tourism-plan"}.pdf`;
}

function buildPlanPdfHtml(plan) {
  const aiPlan = plan.plan_details_json || null;
  const title = getPlanTitle(plan, aiPlan);
  const fileName = getPdfFileName(title);
  const generatedOn = new Date().toLocaleDateString(undefined, {
    year: "numeric",
    month: "long",
    day: "numeric",
  });

  const details = [
    ["Days", plan.days],
    ["Budget", `${plan.budget ?? 0} BHD`],
    ["People", plan.people_count || 1],
    ["Status", plan.status],
    ["Generated by AI", plan.generated_by_ai ? "Yes" : "No"],
  ]
    .map(
      ([label, value]) => `
        <div class="stat">
          <span>${escapeHtml(label)}</span>
          <strong>${formatPdfValue(value)}</strong>
        </div>
      `
    )
    .join("");

  const days = Array.isArray(aiPlan?.days)
    ? aiPlan.days
      .map((day) => {
        const activities = Array.isArray(day.activities)
          ? day.activities
            .map(
              (activity) => `
                    <article class="activity">
                      <div class="activity-head">
                        <h4>${formatPdfValue(activity.name, "Activity")}</h4>
                        <span>${formatPdfValue(activity.type)}</span>
                      </div>
                      <p>${formatPdfValue(activity.notes, "No notes available.")}</p>
                      <div class="meta">
                        <span>${formatPdfValue(activity.time)}</span>
                        <span>${formatPdfValue(activity.estimated_cost_bhd ?? 0)} BHD</span>
                      </div>
                      ${activity.location_area
                  ? `<p class="location">${formatPdfValue(
                    activity.location_name || activity.name
                  )} - ${formatPdfValue(activity.location_area)}</p>`
                  : ""
                }
                    </article>
                  `
            )
            .join("")
          : "";

        return `
            <section class="section">
              <h3>Day ${formatPdfValue(day.day_number)}: ${formatPdfValue(
          day.theme,
          "Plan"
        )}</h3>
              <div class="activities">
                ${activities || "<p>No activities for this day.</p>"}
              </div>
            </section>
          `;
      })
      .join("")
    : "";

  const tips = Array.isArray(aiPlan?.tips)
    ? aiPlan.tips.map((tip) => `<li>${formatPdfValue(tip)}</li>`).join("")
    : "";

  return `
    <!doctype html>
    <html>
      <head>
        <meta charset="utf-8" />
        <title>${escapeHtml(fileName)}</title>
        <style>
          @page {
            size: A4;
            margin: 16mm;
          }

          * {
            box-sizing: border-box;
          }

          body {
            margin: 0;
            color: #1a1410;
            background: #fff;
            font-family: Arial, sans-serif;
            line-height: 1.55;
          }

          .document {
            max-width: 820px;
            margin: 0 auto;
          }

          .hero {
            border-bottom: 3px solid #c01230;
            padding-bottom: 20px;
            margin-bottom: 24px;
          }

          .brand {
            color: #c01230;
            font-weight: 800;
            letter-spacing: 0.08em;
            text-transform: uppercase;
            font-size: 12px;
          }

          h1 {
            margin: 8px 0;
            font-size: 34px;
            line-height: 1.15;
          }

          h2,
          h3,
          h4,
          p {
            margin-top: 0;
          }

          .summary {
            color: #5f4b43;
            margin-bottom: 0;
          }

          .stats {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 12px;
            margin: 20px 0 26px;
          }

          .stat,
          .activity {
            border: 1px solid #eadbd4;
            border-radius: 12px;
            padding: 14px;
            break-inside: avoid;
          }

          .stat span,
          .meta,
          .location,
          .small {
            color: #7a6058;
            font-size: 13px;
          }

          .stat strong {
            display: block;
            color: #1a1410;
            font-size: 17px;
            margin-top: 4px;
          }

          .section {
            margin-top: 26px;
            break-inside: avoid;
          }

          .section h3,
          .block h2 {
            color: #c01230;
            border-bottom: 1px solid #eadbd4;
            padding-bottom: 8px;
            margin-bottom: 14px;
          }

          .activities {
            display: grid;
            gap: 12px;
          }

          .activity-head {
            display: flex;
            justify-content: space-between;
            gap: 12px;
            align-items: flex-start;
          }

          .activity-head h4 {
            margin-bottom: 6px;
            font-size: 17px;
          }

          .activity-head span {
            color: #c01230;
            background: #fff0ec;
            border: 1px solid #f0d3cb;
            border-radius: 999px;
            padding: 4px 8px;
            font-size: 12px;
            font-weight: 700;
            white-space: nowrap;
          }

          .meta {
            display: flex;
            justify-content: space-between;
            gap: 12px;
            margin-top: 12px;
          }

          ul {
            padding-left: 22px;
          }

          li {
            margin-bottom: 8px;
          }

          .download-note {
            margin-top: 24px;
          }

          @media print {
            .download-note {
              display: none;
            }
          }
        </style>
      </head>
      <body>
        <main class="document">
          <header class="hero">
            <div class="brand">Alsaeh.bh Tourism Plan</div>
            <h1>${formatPdfValue(title)}</h1>
            <p class="summary">${formatPdfValue(aiPlan?.summary, "Generated tourism plan for Bahrain.")
    }</p>
            <p class="small">Prepared on ${escapeHtml(generatedOn)}</p>
          </header>

          <section class="stats">
            ${details}
          </section>

          <section class="block">
            <h2>Plan Preferences</h2>
            <p><strong>Preferences:</strong> ${formatPdfValue(plan.preferences)}</p>
          </section>

          ${aiPlan
      ? `
                <section class="block">
                  <h2>${formatPdfValue(
        aiPlan.title,
        "AI Generated Itinerary"
      )}</h2>
                  <p><strong>Estimated budget:</strong> ${formatPdfValue(
        aiPlan.estimated_total_budget_bhd ?? plan.budget ?? 0
      )} BHD</p>
                </section>
                ${days}
                ${tips
        ? `<section class="section"><h3>Tips</h3><ul>${tips}</ul></section>`
        : ""
      }
              `
      : ""
    }

          <p class="download-note">Use the print dialog to save this plan as ${escapeHtml(
      fileName
    )}.</p>
        </main>
        <script>
          window.addEventListener("load", () => {
            window.focus();
            setTimeout(() => window.print(), 250);
          });
        </script>
      </body>
    </html>
  `;
}

const CATEGORIES_CACHE_KEY = "place_categories";
const PLANS_CACHE_KEY = "dashboard_plans";

const integerInputPattern = /^\d*$/;
const budgetInputPattern = /^\d*(?:\.\d{0,3})?$/;
const dayPattern = /^(?:[1-9]|1[0-4])$/;
const peoplePattern = /^(?:[1-9]|[1-4][0-9]|50)$/;
const budgetPattern = /^(?:0|[1-9]\d*)(?:\.\d{1,3})?$/;

function updateIntegerField(setForm, field, value) {
  if (!integerInputPattern.test(value)) return;
  setForm((currentForm) => ({ ...currentForm, [field]: value }));
}

function updateBudgetField(setForm, value) {
  if (!budgetInputPattern.test(value)) return;
  setForm((currentForm) => ({ ...currentForm, budget: value }));
}

function splitCommaList(value) {
  return String(value || "")
    .split(",")
    .map((item) => item.trim())
    .filter(Boolean);
}

function getPreferenceSection(value, label) {
  const text = String(value || "");
  const pattern = new RegExp(`${label}:\\s*([\\s\\S]*?)(?=\\.\\s*(?:Preferences|Extra preferences|Constraints):|$)`, "i");
  return text.match(pattern)?.[1]?.trim() || "";
}

function parsePlanPreferences(data) {
  const preferenceText = data.preferences || "";
  const selectedText =
    getPreferenceSection(preferenceText, "Preferences") ||
    data.category ||
    data.user_interests ||
    "";

  return {
    selected_preferences: splitCommaList(selectedText),
    extra_preferences:
      getPreferenceSection(preferenceText, "Extra preferences") ||
      (/^\s*(?:Preferences|Constraints):/i.test(preferenceText)
        ? ""
        : preferenceText),
    constraints: getPreferenceSection(preferenceText, "Constraints"),
  };
}

function getActivityIcon(activity) {
  const type = String(activity?.type || activity?.category || "").toLowerCase();
  const name = String(activity?.name || "").toLowerCase();
  const text = `${type} ${name}`;

  if (/beach|sea|zallaq|island/.test(text)) return "🏖️";
  if (/museum|heritage|historical|fort|culture/.test(text)) return "🏛️";
  if (/restaurant|dining|food|cafe|coffee/.test(text)) return "🍽️";
  if (/mall|shopping|market|souq/.test(text)) return "🛍️";
  if (/mosque|religious/.test(text)) return "🕌";
  if (/park|garden|nature/.test(text)) return "🌿";
  if (/activity|adventure|experience/.test(text)) return "✨";

  return "📍";
}

function formatActivityValue(value) {
  if (value === null || value === undefined || value === "") return null;
  if (Array.isArray(value)) return value.filter(Boolean).join(", ");
  if (typeof value === "object") return JSON.stringify(value);
  return String(value);
}

function ActivityDetail({ label, value }) {
  const formattedValue = formatActivityValue(value);
  if (!formattedValue) return null;

  return (
    <div className={styles.activityDetailItem}>
      <span>{label}</span>
      <strong>{formattedValue}</strong>
    </div>
  );
}

function ActivityAccordion({ activity, activityId, ui }) {
  const [open, setOpen] = useState(false);
  const hiddenExtraKeys = new Set([
    "time",
    "name",
    "type",
    "category",
    "location_name",
    "location_area",
    "google_maps_query",
    "google_maps_url",
    "estimated_cost_bhd",
    "price",
    "cost",
    "opening_hours",
    "description",
    "notes",
  ]);
  const extraDetails = Object.entries(activity || {}).filter(
    ([key, value]) => !hiddenExtraKeys.has(key) && formatActivityValue(value)
  );

  return (
    <div className={styles.activityAccordion}>
      <button
        type="button"
        className={styles.activityAccordionTrigger}
        onClick={() => setOpen((current) => !current)}
        aria-expanded={open}
        aria-controls={`${activityId}-details`}
      >
        <span className={styles.activityIcon}>{getActivityIcon(activity)}</span>
        <span className={styles.activityTitle}>
          {activity?.name || activity?.location_name || "Activity"}
        </span>
        <span className={styles.activityExpandIndicator}>
          {open ? "-" : "+"}
        </span>
      </button>

      {open && (
        <div id={`${activityId}-details`} className={styles.activityDetails}>
          {activity?.notes && (
            <p className={styles.activityDescription}>{activity.notes}</p>
          )}

          {activity?.description && activity.description !== activity.notes && (
            <p className={styles.activityDescription}>{activity.description}</p>
          )}

          <div className={styles.activityDetailGrid}>
            <ActivityDetail label={ui.time} value={activity?.time} />
            <ActivityDetail
              label={ui.estimatedCost}
              value={
                activity?.estimated_cost_bhd !== undefined
                  ? `${activity.estimated_cost_bhd} BHD`
                  : activity?.price || activity?.cost
              }
            />
            <ActivityDetail label={ui.openingHours} value={activity?.opening_hours} />
            <ActivityDetail label={ui.category} value={activity?.type || activity?.category} />
            <ActivityDetail label={ui.location} value={activity?.location_name} />
            <ActivityDetail label={ui.area} value={activity?.location_area} />
            <ActivityDetail label={ui.mapSearch} value={activity?.google_maps_query} />

            {extraDetails.map(([key, value]) => (
              <ActivityDetail
                key={key}
                label={key.replaceAll("_", " ")}
                value={value}
              />
            ))}
          </div>

          {activity?.google_maps_url && (
            <a
              href={activity.google_maps_url}
              target="_blank"
              rel="noopener noreferrer"
              className={styles.activityMapButton}
            >
              {ui.googleMaps}
            </a>
          )}
        </div>
      )}
    </div>
  );
}

function PlanDayCard({ day, ui }) {
  const activities = Array.isArray(day?.activities) ? day.activities : [];

  return (
    <section className={styles.planDayCard}>
      <div className={styles.planDayChrome}>
        <span />
        <span />
        <span />
      </div>

      <div className={styles.planDayHeader}>
        <div>
          <span className={styles.planDayPill}>{ui.personalizedForYou}</span>
          <h3>
            {ui.day} {day?.day_number || ""}
            {day?.theme ? `: ${day.theme}` : ""}
          </h3>
        </div>
      </div>

      {activities.length > 0 ? (
        <div className={styles.planDayActivities}>
          {activities.map((activity, index) => (
            <ActivityAccordion
              key={`${day?.day_number || "day"}-${index}-${activity?.name || "activity"}`}
              activity={activity}
              activityId={`day-${day?.day_number || "x"}-activity-${index}`}
              ui={ui}
            />
          ))}
        </div>
      ) : (
        <p className={styles.planDayEmpty}>{ui.noActivitiesDay}</p>
      )}
    </section>
  );
}

export default function PlanDetailsPage() {
  const { id } = useParams();
  const router = useRouter();
  const chatEndRef = useRef(null);
  const { lang, dir } = useLanguage();

  const [plan, setPlan] = useState(null);
  const [form, setForm] = useState({
    title: "",
    days: "",
    budget: "",
    people_count: "",
    selected_preferences: [],
    extra_preferences: "",
    constraints: "",
    travel_styles: "",
    place: "",
  });
  const [categories, setCategories] = useState([]);
  const [preferencesOpen, setPreferencesOpen] = useState(false);
  const [loadingCategories, setLoadingCategories] = useState(true);

  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [deleting, setDeleting] = useState(false);
  const [editMode, setEditMode] = useState(false);
  const [error, setError] = useState("");

  const [chatMessage, setChatMessage] = useState("");
  const [chatLoading, setChatLoading] = useState(false);
  const [chatMessages, setChatMessages] = useState([]);

  const ui = {
    en: {
      loading: "Loading...",
      notFound: "Plan not found",
      untitledPlan: "Untitled Plan",
      subtitle: "View, edit, and improve your tourism plan with the AI assistant.",
      downloadPdf: "Download PDF",
      editPlan: "Edit Plan",
      deletePlan: "Delete Plan",
      deleting: "Deleting...",
      editingPlan: "Editing plan",
      planDetails: "Plan Details",
      editSubtitle:
        "Update the core trip information, preferences, and travel context.",
      planTitle: "Plan Title",
      planTitlePlaceholder: "Relaxed Bahrain Weekend",
      days: "Days",
      numberOfDays: "Number of Days",
      daysHint: "Whole numbers only, from 1 to 14.",
      budget: "Budget",
      budgetBhd: "Budget (BHD)",
      budgetHint: "Use numbers only. Decimals can include up to 3 digits.",
      people: "People",
      numberOfPeople: "Number of People",
      status: "Status",
      generatedByAi: "Generated by AI",
      yes: "Yes",
      no: "No",
      preferences: "Preferences",
      extraPreferences: "Extra Preferences",
      constraints: "Constraints",
      travelStyle: "Travel Style",
      selectTravelStyle: "Select travel style",
      relaxed: "Relaxed",
      adventure: "Adventure",
      family: "Family-friendly",
      friends: "Friends",
      soloTravel: "Solo Travel",
      cultural: "Cultural",
      budgetFriendly: "Budget-friendly",
      luxury: "Luxury",
      selected: "selected",
      loadingPreferences: "Loading preferences...",
      selectPreferences: "Select one or more preferences",
      selectAllPreferences: "Select all preferences",
      noPreferences: "No preferences available",
      extraPreferencesPlaceholder:
        "Example: low walking, indoor preferred, suitable for family",
      constraintsPlaceholder:
        "Example: indoor preferred, no expensive restaurants",
      constraintsHint: "Separate constraints with commas.",
      cancel: "Cancel",
      saveChanges: "Save Changes",
      rebuilding: "Rebuilding plan...",
      estimatedBudget: "Estimated Budget",
      aiItinerary: "AI Generated Itinerary",
      noSummary: "No summary available.",
      tips: "Tips",
      time: "Time",
      estimatedCost: "Estimated cost",
      openingHours: "Opening Hours",
      category: "Category",
      location: "Location",
      area: "Area",
      mapSearch: "Map search",
      googleMaps: "Open in Google Maps",
      personalizedForYou: "Personalized for you",
      day: "Day",
      noActivitiesDay: "No activities available for this day.",
      aiTerminal: "AI Trip Terminal",
      aiTerminalSubtitle: "Ask for advice or request changes to this plan.",
      online: "online",
      chatEmpty: "Ask me about this trip, or tell me what you want to change.",
      thinking: "Thinking...",
      chatPlaceholder: "ask for advice or request a change...",
      send: "Send",
      updateFailed: "Failed to update plan",
      deleteFailed: "Failed to delete plan",
      unableToConnect: "Unable to connect to server",
      confirmDelete: "Are you sure you want to delete this plan?",
      allowPopups: "Please allow pop-ups to download this plan as a PDF.",
      aiBusy: "AI service is busy. Please try again.",
      done: "Done.",
      daysError: "Number of days must be a whole number from 1 to 14.",
      budgetError:
        "Budget must be a positive BHD amount with up to 3 decimal places.",
      peopleError: "Number of people must be a whole number from 1 to 50.",
      preferencesError: "Select at least one preference.",
    },
    ar: {
      loading: "جاري التحميل...",
      notFound: "لم يتم العثور على الخطة",
      untitledPlan: "خطة بدون عنوان",
      subtitle: "اعرض وعدّل وحسّن خطتك السياحية بمساعدة الذكاء الاصطناعي.",
      downloadPdf: "تنزيل PDF",
      editPlan: "تعديل الخطة",
      deletePlan: "حذف الخطة",
      deleting: "جاري الحذف...",
      editingPlan: "تعديل الخطة",
      planDetails: "تفاصيل الخطة",
      editSubtitle:
        "حدّث معلومات الرحلة والتفضيلات وسياق السفر الأساسي.",
      planTitle: "عنوان الخطة",
      planTitlePlaceholder: "عطلة هادئة في البحرين",
      days: "الأيام",
      numberOfDays: "عدد الأيام",
      daysHint: "أرقام صحيحة فقط من 1 إلى 14.",
      budget: "الميزانية",
      budgetBhd: "الميزانية (BHD)",
      budgetHint: "استخدم الأرقام فقط. يمكن أن تحتوي الكسور على 3 خانات كحد أقصى.",
      people: "الأشخاص",
      numberOfPeople: "عدد الأشخاص",
      status: "الحالة",
      generatedByAi: "مولدة بالذكاء الاصطناعي",
      yes: "نعم",
      no: "لا",
      preferences: "التفضيلات",
      extraPreferences: "تفضيلات إضافية",
      constraints: "القيود",
      travelStyle: "نمط الرحلة",
      selectTravelStyle: "اختر نمط الرحلة",
      relaxed: "هادئة",
      adventure: "مغامرة",
      family: "مناسبة للعائلة",
      friends: "أصدقاء",
      soloTravel: "سفر فردي",
      cultural: "ثقافية",
      budgetFriendly: "اقتصادية",
      luxury: "فاخرة",
      selected: "محدد",
      loadingPreferences: "جاري تحميل التفضيلات...",
      selectPreferences: "اختر تفضيلاً واحداً أو أكثر",
      selectAllPreferences: "تحديد كل التفضيلات",
      noPreferences: "لا توجد تفضيلات متاحة",
      extraPreferencesPlaceholder:
        "مثال: مشي قليل، أماكن داخلية، مناسبة للعائلة",
      constraintsPlaceholder:
        "مثال: أماكن داخلية، بدون مطاعم غالية",
      constraintsHint: "افصل بين القيود باستخدام الفواصل.",
      cancel: "إلغاء",
      saveChanges: "حفظ التغييرات",
      rebuilding: "جاري إعادة بناء الخطة...",
      estimatedBudget: "الميزانية المتوقعة",
      aiItinerary: "جدول مولد بالذكاء الاصطناعي",
      noSummary: "لا يوجد ملخص متاح.",
      tips: "نصائح",
      time: "الوقت",
      estimatedCost: "التكلفة المتوقعة",
      openingHours: "ساعات العمل",
      category: "التصنيف",
      location: "الموقع",
      area: "المنطقة",
      mapSearch: "بحث الخريطة",
      googleMaps: "فتح في خرائط Google",
      personalizedForYou: "مخصص لك",
      day: "اليوم",
      noActivitiesDay: "لا توجد أنشطة متاحة لهذا اليوم.",
      aiTerminal: "محادثة الرحلة الذكية",
      aiTerminalSubtitle: "اطلب نصيحة أو تغييرات على هذه الخطة.",
      online: "متصل",
      chatEmpty: "اسألني عن هذه الرحلة أو أخبرني بما تريد تغييره.",
      thinking: "جاري التفكير...",
      chatPlaceholder: "اطلب نصيحة أو تغييراً...",
      send: "إرسال",
      updateFailed: "فشل تحديث الخطة",
      deleteFailed: "فشل حذف الخطة",
      unableToConnect: "تعذر الاتصال بالخادم",
      confirmDelete: "هل أنت متأكد من حذف هذه الخطة؟",
      allowPopups: "يرجى السماح بالنوافذ المنبثقة لتنزيل الخطة كملف PDF.",
      aiBusy: "خدمة الذكاء الاصطناعي مشغولة. يرجى المحاولة مرة أخرى.",
      done: "تم.",
      daysError: "يجب أن يكون عدد الأيام رقماً صحيحاً من 1 إلى 14.",
      budgetError:
        "يجب أن تكون الميزانية مبلغاً موجباً بالدينار مع 3 خانات عشرية كحد أقصى.",
      peopleError: "يجب أن يكون عدد الأشخاص رقماً صحيحاً من 1 إلى 50.",
      preferencesError: "اختر تفضيلاً واحداً على الأقل.",
    },
  }[lang];

  const fillForm = useCallback((data) => {
    const planPreferences = parsePlanPreferences(data);

    setForm({
      title: data.title || "",
      days: data.days || "",
      budget: data.budget ?? "",
      people_count: data.people_count || 1,
      selected_preferences: planPreferences.selected_preferences,
      extra_preferences: planPreferences.extra_preferences,
      constraints: planPreferences.constraints,
      travel_styles: data.travel_styles || "",
      place: data.place || "",
    });
  }, []);

  const loadPlan = useCallback(async (tokenFromInit = null) => {
    try {
      const token = tokenFromInit || (await getAccessToken());

      if (!token) {
        router.replace("/login");
        return;
      }

      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/plans/${id}`, {
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      if (!res.ok) {
        router.replace("/dashboard");
        return;
      }

      const data = await res.json();
      setPlan(data);
      fillForm(data);
      sessionStorage.setItem(`plan_${id}`, JSON.stringify(data));
    } catch (error) {
      console.error("Load plan error:", error);
      router.replace("/dashboard");
    } finally {
      setLoading(false);
    }
  }, [fillForm, id, router]);

  useEffect(() => {
    async function initPage() {
      const cacheKey = `plan_${id}`;
      const cached = sessionStorage.getItem(cacheKey);
      if (cached) {
        try {
          const cachedPlan = JSON.parse(cached);
          setPlan(cachedPlan);
          fillForm(cachedPlan);
          setLoading(false);
        } catch {
          sessionStorage.removeItem(cacheKey);
        }
      }

      const token = await getAccessToken();

      if (!token) {
        router.replace("/login");
        return;
      }

      await loadPlan(token);
    }

    initPage();
  }, [fillForm, id, loadPlan, router]);

  useEffect(() => {
    async function loadCategories() {
      const cached = sessionStorage.getItem(CATEGORIES_CACHE_KEY);
      if (cached) {
        try {
          setCategories(JSON.parse(cached));
          setLoadingCategories(false);
        } catch {
          sessionStorage.removeItem(CATEGORIES_CACHE_KEY);
        }
      }

      try {
        const token = await getAccessToken();

        if (!token) return;

        const res = await fetch(
          `${process.env.NEXT_PUBLIC_API_URL}/place-categories`,
          {
            headers: {
              Authorization: `Bearer ${token}`,
            },
          }
        );

        if (res.ok) {
          const data = await res.json();
          setCategories(data);
          sessionStorage.setItem(CATEGORIES_CACHE_KEY, JSON.stringify(data));
        }
      } catch (error) {
        console.error("Load categories error:", error);
      } finally {
        setLoadingCategories(false);
      }
    }

    loadCategories();
  }, []);
  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [chatMessages]);

  const preferenceOptions = categories.map((category) => ({
    id: category.id,
    value: category.name,
    label: category.name.replaceAll("_", " "),
  }));
  const selectedPreferenceLabels = form.selected_preferences.map((value) => {
    const option = preferenceOptions.find((category) => category.value === value);
    return option?.label || value.replaceAll("_", " ");
  });
  const allPreferencesSelected =
    preferenceOptions.length > 0 &&
    preferenceOptions.every((category) =>
      form.selected_preferences.includes(category.value)
    );

  function updatePreference(value, checked) {
    setForm((currentForm) => {
      const current = currentForm.selected_preferences;
      const selected_preferences = checked
        ? Array.from(new Set([...current, value]))
        : current.filter((item) => item !== value);

      return { ...currentForm, selected_preferences };
    });
  }

  function toggleAllPreferences(checked) {
    setForm((currentForm) => ({
      ...currentForm,
      selected_preferences: checked
        ? preferenceOptions.map((category) => category.value)
        : [],
    }));
  }

  function validateEditForm() {
    if (!dayPattern.test(String(form.days))) {
      return ui.daysError;
    }

    if (form.budget !== "" && !budgetPattern.test(String(form.budget))) {
      return ui.budgetError;
    }

    if (!peoplePattern.test(String(form.people_count))) {
      return ui.peopleError;
    }

    if (form.selected_preferences.length === 0) {
      return ui.preferencesError;
    }

    return "";
  }

  function applyUpdatedPlan(updatedPlan) {
    if (!updatedPlan) return;

    setPlan(updatedPlan);
    fillForm(updatedPlan);
    sessionStorage.setItem(`plan_${id}`, JSON.stringify(updatedPlan));
  }

  async function handleUpdate(e) {
    e.preventDefault();
    setError("");

    const validationError = validateEditForm();
    if (validationError) {
      setError(validationError);
      return;
    }

    setSaving(true);

    try {
      const token = await getAccessToken();

      if (!token) {
        router.replace("/login");
        return;
      }

      const constraintsList = splitCommaList(form.constraints);

      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/plans/${id}`, {
        method: "PUT",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          title: form.title,
          days: Number(form.days),
          budget: form.budget === "" ? null : Number(form.budget),
          people_count: Number(form.people_count),
          preferences: form.selected_preferences,
          extra_preferences: form.extra_preferences || null,
          constraints: constraintsList,
          travel_styles: form.travel_styles || null,
          place: null,
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(getErrorMessage(data.detail, ui.updateFailed));
        return;
      }

      applyUpdatedPlan(data.plan);
      sessionStorage.removeItem(PLANS_CACHE_KEY);
      setEditMode(false);
    } catch (error) {
      console.error("Update plan error:", error);
      setError(ui.unableToConnect);
    } finally {
      setSaving(false);
    }
  }

  async function handleDelete() {
    const confirmed = window.confirm(ui.confirmDelete);
    if (!confirmed) return;

    setDeleting(true);
    setError("");

    try {
      const token = await getAccessToken();

      if (!token) {
        router.replace("/login");
        return;
      }

      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/plans/${id}`, {
        method: "DELETE",
        headers: {
          Authorization: `Bearer ${token}`,
        },
      });

      const data = await res.json();

      if (!res.ok) {
        setError(getErrorMessage(data.detail, ui.deleteFailed));
        return;
      }

      sessionStorage.removeItem(`plan_${id}`);
      sessionStorage.removeItem(PLANS_CACHE_KEY);
      router.replace("/dashboard");
    } catch (error) {
      console.error("Delete plan error:", error);
      setError(ui.unableToConnect);
    } finally {
      setDeleting(false);
    }
  }

  function handleDownloadPdf() {
    if (!plan) return;

    const pdfWindow = window.open("", "_blank");

    if (!pdfWindow) {
      setError(ui.allowPopups);
      return;
    }

    pdfWindow.document.open();
    pdfWindow.document.write(buildPlanPdfHtml(plan));
    pdfWindow.document.close();
  }

  async function handleChatSubmit(e) {
    e.preventDefault();

    if (!chatMessage.trim()) return;

    const userText = chatMessage.trim();

    setChatMessages((prev) => [...prev, { sender: "user", text: userText }]);
    setChatMessage("");
    setChatLoading(true);

    try {
      const token = await getAccessToken();

      if (!token) {
        router.replace("/login");
        return;
      }

      const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/ai/plan-chat`, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${token}`,
        },
        body: JSON.stringify({
          plan_id: Number(id),
          message: userText,
          language: "auto",
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setChatMessages((prev) => [
          ...prev,
          {
            sender: "assistant",
            text:
              typeof data.detail === "string"
                ? data.detail
                : ui.aiBusy,
          },
        ]);
        return;
      }

      setChatMessages((prev) => [
        ...prev,
        { sender: "assistant", text: data.message || ui.done },
      ]);

      if (data.updated) {
        applyUpdatedPlan(data.plan);
        sessionStorage.removeItem(PLANS_CACHE_KEY);
      }
    } catch (error) {
      console.error("Chat error:", error);
      setChatMessages((prev) => [
        ...prev,
        { sender: "assistant", text: ui.unableToConnect },
      ]);
    } finally {
      setChatLoading(false);
    }
  }

  if (loading) {
    return <div className={styles.emptyState}>{ui.loading}</div>;
  }

  if (!plan) {
    return <div className={styles.emptyState}>{ui.notFound}</div>;
  }

  const aiPlan = plan.plan_details_json || null;

  return (
    <div className={styles.pageContent} dir={dir}>
      <div className={styles.detailsHeader}>
        <div>
          <h1 className={styles.pageTitle}>
            {plan.title || aiPlan?.title || ui.untitledPlan}
          </h1>
          <p className={styles.pageSubtitle}>
            {ui.subtitle}
          </p>
        </div>

        <div className={styles.detailsActions}>
          {!editMode && (
            <>
              <button
                className={styles.secondaryActionButton}
                onClick={handleDownloadPdf}
              >
                {ui.downloadPdf}
              </button>

              <button
                className={styles.secondaryActionButton}
                onClick={() => setEditMode(true)}
              >
                {ui.editPlan}
              </button>
            </>
          )}

          <button
            className={styles.deleteButton}
            onClick={handleDelete}
            disabled={deleting}
          >
            {deleting ? ui.deleting : ui.deletePlan}
          </button>
        </div>
      </div>

      {error && <p className={styles.error}>{error}</p>}

      <div
        className={`${styles.planDetailsLayout} ${editMode ? styles.editPlanLayout : ""
          }`}
      >
        <div className={styles.planDetailsMain}>
          {editMode ? (
            <form onSubmit={handleUpdate} className={`${styles.detailsCard} ${styles.editPlanCard}`}>
              <div className={styles.editPlanHeader}>
                <span className={styles.createBadge}>{ui.editingPlan}</span>
                <h2 className={styles.blockTitle}>{ui.planDetails}</h2>
                <p className={styles.pageSubtitle}>
                  {ui.editSubtitle}
                </p>
              </div>

              <div className={styles.aiFormGrid}>
                <div className={styles.aiField}>
                  <label>{ui.planTitle}</label>
                  <input
                    value={form.title}
                    placeholder={ui.planTitlePlaceholder}
                    onChange={(e) => setForm({ ...form, title: e.target.value })}
                    required
                  />
                </div>

                <div className={styles.aiField}>
                  <label>{ui.numberOfDays}</label>
                  <input
                    type="text"
                    inputMode="numeric"
                    pattern="[0-9]*"
                    value={form.days}
                    placeholder="2"
                    onChange={(e) =>
                      updateIntegerField(setForm, "days", e.target.value)
                    }
                    required
                  />
                  <small>{ui.daysHint}</small>
                </div>

                <div className={styles.aiField}>
                  <label>{ui.budgetBhd}</label>
                  <input
                    type="text"
                    inputMode="decimal"
                    value={form.budget}
                    placeholder="195.650"
                    onChange={(e) => updateBudgetField(setForm, e.target.value)}
                  />
                  <small>{ui.budgetHint}</small>
                </div>

                <div className={styles.aiField}>
                  <label>{ui.numberOfPeople}</label>
                  <input
                    type="text"
                    inputMode="numeric"
                    pattern="[0-9]*"
                    value={form.people_count}
                    placeholder="2"
                    onChange={(e) =>
                      updateIntegerField(setForm, "people_count", e.target.value)
                    }
                    required
                  />
                </div>

                <div className={styles.aiField}>
                  <label>{ui.travelStyle}</label>
                  <select
                    value={form.travel_styles}
                    onChange={(e) =>
                      setForm({ ...form, travel_styles: e.target.value })
                    }
                  >
                    <option value="">{ui.selectTravelStyle}</option>
                    <option value="relaxed">{ui.relaxed}</option>
                    <option value="adventure">{ui.adventure}</option>
                    <option value="family-friendly">{ui.family}</option>
                    <option value="friends">{ui.friends}</option>
                    <option value="solo-travel">{ui.soloTravel}</option>
                    <option value="cultural">{ui.cultural}</option>
                    <option value="budget-friendly">{ui.budgetFriendly}</option>
                    <option value="luxury">{ui.luxury}</option>
                  </select>
                </div>
              </div>

              <div className={styles.aiField}>
                <label>{ui.preferences}</label>
                <div className={styles.preferenceDropdown}>
                  <button
                    type="button"
                    className={styles.preferenceTrigger}
                    onClick={() => setPreferencesOpen((open) => !open)}
                    aria-expanded={preferencesOpen}
                  >
                    <span>
                      {selectedPreferenceLabels.length
                        ? `${selectedPreferenceLabels.length} ${ui.selected}`
                        : loadingCategories
                          ? ui.loadingPreferences
                          : ui.selectPreferences}
                    </span>
                    <span className={styles.preferenceChevron}>v</span>
                  </button>

                  {selectedPreferenceLabels.length > 0 && (
                    <div className={styles.preferenceChips}>
                      {selectedPreferenceLabels.map((label) => (
                        <span key={label}>{label}</span>
                      ))}
                    </div>
                  )}

                  {preferencesOpen && (
                    <div className={styles.preferencePanel}>
                      <label className={styles.preferenceOption}>
                        <input
                          type="checkbox"
                          checked={allPreferencesSelected}
                          onChange={(e) => toggleAllPreferences(e.target.checked)}
                          disabled={preferenceOptions.length === 0}
                        />
                        <span>{ui.selectAllPreferences}</span>
                      </label>

                      <div className={styles.preferenceDivider} />

                      {preferenceOptions.length === 0 ? (
                        <p className={styles.preferenceEmpty}>
                          {loadingCategories
                            ? ui.loadingPreferences
                            : ui.noPreferences}
                        </p>
                      ) : (
                        preferenceOptions.map((category) => (
                          <label
                            key={category.id}
                            className={styles.preferenceOption}
                          >
                            <input
                              type="checkbox"
                              checked={form.selected_preferences.includes(
                                category.value
                              )}
                              onChange={(e) =>
                                updatePreference(category.value, e.target.checked)
                              }
                            />
                            <span>{category.label}</span>
                          </label>
                        ))
                      )}
                    </div>
                  )}
                </div>
              </div>

              <div className={styles.aiField}>
                <label>{ui.extraPreferences}</label>
                <textarea
                  value={form.extra_preferences}
                  placeholder={ui.extraPreferencesPlaceholder}
                  onChange={(e) =>
                    setForm({ ...form, extra_preferences: e.target.value })
                  }
                />
              </div>

              <div className={styles.aiField}>
                <label>{ui.constraints}</label>
                <input
                  value={form.constraints}
                  placeholder={ui.constraintsPlaceholder}
                  onChange={(e) =>
                    setForm({ ...form, constraints: e.target.value })
                  }
                />
                <small>{ui.constraintsHint}</small>
              </div>

              <div className={styles.detailsActions}>
                <button
                  type="button"
                  className={styles.cancelButton}
                  onClick={() => {
                    fillForm(plan);
                    setEditMode(false);
                  }}
                >
                  {ui.cancel}
                </button>

                <button
                  type="submit"
                  className={styles.primaryButton}
                  disabled={saving}
                >
                  {saving ? ui.rebuilding : ui.saveChanges}
                </button>
              </div>
            </form>
          ) : (
            <>
              <div className={styles.detailsCard}>
                <div className={styles.detailsGrid}>
                  <div className={styles.detailItem}>
                    <span className={styles.detailLabel}>{ui.days}</span>
                    <strong>{plan.days}</strong>
                  </div>

                  <div className={styles.detailItem}>
                    <span className={styles.detailLabel}>{ui.budget}</span>
                    <strong>{plan.budget ?? 0} BHD</strong>
                  </div>

                  <div className={styles.detailItem}>
                    <span className={styles.detailLabel}>{ui.people}</span>
                    <strong>{plan.people_count || 1}</strong>
                  </div>
                </div>

                <div className={styles.detailBlock}>
                  <h3 className={styles.blockTitle}>{ui.preferences}</h3>
                  <p>{plan.preferences || "-"}</p>
                </div>

              </div>

              {aiPlan && (
                <div className={styles.detailsCard} style={{ marginTop: "22px" }}>
                  <h2 className={styles.blockTitle}>
                    {aiPlan.title || ui.aiItinerary}
                  </h2>

                  <p className={styles.pageSubtitle}>
                    {aiPlan.summary || ui.noSummary}
                  </p>

                  <div className={styles.detailsGrid} style={{ marginTop: "20px" }}>
                    <div className={styles.detailItem}>
                      <span className={styles.detailLabel}>{ui.estimatedBudget}</span>
                      <strong>
                        {aiPlan.estimated_total_budget_bhd ?? plan.budget ?? 0} BHD
                      </strong>
                    </div>

                    <div className={styles.detailItem}>
                      <span className={styles.detailLabel}>{ui.people}</span>
                      <strong>{plan.people_count || 1}</strong>
                    </div>
                  </div>

                  {Array.isArray(aiPlan.days) && (
                    <div className={styles.planDayList}>
                      {aiPlan.days.map((day) => (
                        <PlanDayCard key={day.day_number} day={day} ui={ui} />
                      ))}
                    </div>
                  )}

                  {false && Array.isArray(aiPlan.days) &&
                    aiPlan.days.map((day) => (
                      <div key={day.day_number} className={styles.detailBlock}>
                        <h3 className={styles.blockTitle}>
                          Day {day.day_number}: {day.theme}
                        </h3>

                        {Array.isArray(day.activities) &&
                          day.activities.length > 0 ? (
                          <div className={styles.planGrid}>
                            {day.activities.map((activity, index) => (
                              <div key={index} className={styles.planCard}>
                                <div className={styles.planTop}>
                                  <h4 className={styles.planTitle}>
                                    {activity.name}
                                  </h4>
                                  <span className={styles.planStatus}>
                                    {activity.type}
                                  </span>
                                </div>

                                <p className={styles.planDescription}>
                                  {activity.notes}
                                </p>

                                <div className={styles.planMeta}>
                                  <span>{activity.time}</span>
                                  <span>
                                    {activity.estimated_cost_bhd ?? 0} BHD
                                  </span>
                                </div>

                                {activity.location_area && (
                                  <p className={styles.locationText}>
                                    {activity.location_name || activity.name} ·{" "}
                                    {activity.location_area}
                                  </p>
                                )}

                                {activity.google_maps_url && (
                                  <a
                                    href={activity.google_maps_url}
                                    target="_blank"
                                    rel="noopener noreferrer"
                                    className={styles.mapButton}
                                  >
                                    Open in Google Maps
                                  </a>
                                )}
                              </div>
                            ))}
                          </div>
                        ) : (
                          <p>No activities for this day.</p>
                        )}
                      </div>
                    ))}

                  {Array.isArray(aiPlan.tips) && aiPlan.tips.length > 0 && (
                    <div className={styles.detailBlock}>
                      <h3 className={styles.blockTitle}>{ui.tips}</h3>
                      <ul>
                        {aiPlan.tips.map((tip, index) => (
                          <li key={index}>{tip}</li>
                        ))}
                      </ul>
                    </div>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        {!editMode && (
          <aside id="plan-chatbot" className={styles.aiChatPanel}>
            <div className={styles.aiChatHeader}>
              <div className={styles.terminalChrome}>
                <span />
                <span />
                <span />
              </div>
              <div>
                <h3>{ui.aiTerminal}</h3>
                <p>{ui.aiTerminalSubtitle}</p>
              </div>
              <span className={styles.terminalStatus}>{ui.online}</span>
            </div>

            <div className={styles.aiChatMessages}>
              {chatMessages.length === 0 ? (
                <div className={styles.aiChatEmpty}>
                  {ui.chatEmpty}
                </div>
              ) : (
                chatMessages.map((msg, index) => (
                  <div
                    key={index}
                    className={
                      msg.sender === "user"
                        ? styles.userChatBubble
                        : styles.assistantChatBubble
                    }
                  >
                    {msg.text}
                  </div>
                ))
              )}

              {chatLoading && (
                <div className={styles.assistantChatBubble}>{ui.thinking}</div>
              )}

              <div ref={chatEndRef} />
            </div>

            <form onSubmit={handleChatSubmit} className={styles.aiChatForm}>
              <div className={styles.terminalPrompt}>
                <span>&gt;</span>
                <textarea
                  value={chatMessage}
                  placeholder={ui.chatPlaceholder}
                  onChange={(e) => setChatMessage(e.target.value)}
                  disabled={chatLoading}
                />
              </div>

              <button type="submit" disabled={chatLoading || !chatMessage.trim()}>
                {ui.send}
              </button>
            </form>
          </aside>
        )}
      </div>
    </div>
  );
}
